# Autogenerated file
onerror {
	quit -f -code 1
}
vmap -c
if [file exists sim_build/xil_defaultlib] {vdel -lib sim_build/xil_defaultlib -all}
vlib sim_build/xil_defaultlib
vmap xil_defaultlib sim_build/xil_defaultlib
do /home/stud/hm69jare/code/tapasco-sim/simulate_testbench.sim/sim_1/behav/questa/pe_compile.do; do /home/stud/hm69jare/code/tapasco-sim/simulate_testbench.sim/sim_1/behav/questa/pe_elaborate.do;
vsim -lib xil_defaultlib pe_opt -suppress 7061 -suppress 12003 -onfinish exit -pli /home/stud/hm69jare/code/tapasco-sim/.venv/lib64/python3.10/site-packages/cocotb/libs/libcocotbvpi_modelsim.so; # -onfinish exit -pli /home/stud/hm69jare/code/tapasco-sim/.venv/lib64/python3.10/site-packages/cocotb/libs/libcocotbvpi_modelsim.so   sim_build/xil_defaultlib.pe
onbreak resume
