image: tapasco

variables:
  XILINXD_LICENSE_FILE: "/opt/cad/keys/xilinx"

before_script:
  - uname -a
  - echo $SHELL
  - echo $PWD
  - source $PWD/setup.sh
  - source /root/.sdkman/bin/sdkman-init.sh
  - export SBT_OPTS="-Dsbt.global.base=$TAPASCO_HOME/.sbt/ -Dsbt.ivy.home=$TAPASCO_HOME/.ivy2/ -Divy.home=$TAPASCO_HOME/.ivy2/"

stages:
  - toolchain-test
  - hls
  - import
  - compose
  - compose-features
  - dse

scala-test:
  stage: toolchain-test
  script:
    - sbt clean test

.template: &template
  only:
    - "gitlab-ci"
    - "master"
    - /20\d\d\.\d/

sbt-prepare:
  <<: *template
  stage: toolchain-test
  cache:
      untracked: true
      key: "$CI_COMMIT_SHA-$CI_COMMIT_REF_NAME"
      policy: push
  script:
    - sbt assembly

.hls-template: &hls-definition
  <<: *template
  stage: hls
  dependencies:
    - sbt-prepare
  cache:
      untracked: true
      key: "$CI_COMMIT_SHA-$CI_COMMIT_REF_NAME"
      policy: pull
  artifacts:
      when: always
      expire_in: 1 hours
      paths:
        - core
  script:
    - source /opt/cad/$VIVADO_OFFSET/settings64.sh
    - vivado -version
    - |
      if [ ! -d ".ivy2" ]; then
        echo "Cache not available"
        sbt assembly
      fi
    - tapasco -v hls arraysum, arrayinit -a $ARCHS -p $PLATFORMS

.import-template: &import-definition
  <<: *template
  stage: import
  dependencies:
    - sbt-prepare
  cache:
      untracked: true
      key: "$CI_COMMIT_SHA-$CI_COMMIT_REF_NAME"
      policy: pull
  script:
    - source /opt/cad/$VIVADO_OFFSET/settings64.sh
    - |
      if [ ! -d ".ivy2" ]; then
        echo "Cache not available"
        sbt assembly
      fi
    - cd $TAPASCO_HOME/common/ip && zip -r precision_counter.zip precision_counter*
    - tapasco -v import $TAPASCO_HOME/common/ip/precision_counter.zip as 14 -a $ARCHS -p $PLATFORMS

.compose-template: &compose-definition
  <<: *template
  stage: compose
  cache:
      untracked: true
      key: "$CI_COMMIT_SHA-$CI_COMMIT_REF_NAME"
      policy: pull
  script:
    - source /opt/cad/$VIVADO_OFFSET/settings64.sh
    - |
      if [ ! -d ".ivy2" ]; then
        echo "Cache not available"
        sbt assembly
      fi
    - tapasco -v --maxTasks 1 compose [arraysum x 1, arrayupdate x 1] @ 100 MHz -a $ARCHS -p $PLATFORMS

.compose-features-template: &compose-features-definition
  <<: *template
  stage: compose-features
  cache:
      untracked: true
      key: "$CI_COMMIT_SHA-$CI_COMMIT_REF_NAME"
      policy: pull
  script:
    - source /opt/cad/$VIVADO_OFFSET/settings64.sh
    - |
      if [ ! -d ".ivy2" ]; then
        echo "Cache not available"
        sbt assembly
      fi
    - tapasco -v --maxTasks 1 compose [arraysum x 1, arrayupdate x 1] @ 100 MHz -a $ARCHS -p $PLATFORMS --features "$FEATURES"

