/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.0-dev */

#include "status_core.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(tapasco_status_PE, tapasco_status_PE, AUTO)


PB_BIND(tapasco_status_Platform, tapasco_status_Platform, AUTO)


PB_BIND(tapasco_status_Clock, tapasco_status_Clock, AUTO)


PB_BIND(tapasco_status_Version, tapasco_status_Version, AUTO)


PB_BIND(tapasco_status_MemoryArea, tapasco_status_MemoryArea, AUTO)


PB_BIND(tapasco_status_Status, tapasco_status_Status, AUTO)



/* @@protoc_insertion_point(eof) */
