/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.0-dev */

#include "status_core.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(PE, PE, AUTO)


PB_BIND(Platform, Platform, AUTO)


PB_BIND(Clock, Clock, AUTO)


PB_BIND(Version, Version, AUTO)


PB_BIND(Status, Status, AUTO)



/* @@protoc_insertion_point(eof) */
