[package]
name = "tapasco"
version = "1.0.0"
authors = ["Jaco Hofmann <hofmann@esa.tu-darmstadt.de>"]
edition = "2021"

[lib]
crate-type = ["staticlib", "rlib"]

[profile.release]
opt-level = 3
codegen-units = 1
lto = "fat"

[features]
# There are no default features:
default = []
# Necessary when building `tapasco-debug` to make some things accessible that are usually hidden away:
tapasco-debug = []

[dependencies]
log = "0.4.14"
chrono = "0.4.23"
nix = "0.23.1"
memmap = "0.7.0"
getset = "0.1.1"
snafu = "0.7.0"
tonic = "0.8"
prost = "0.11.0"
env_logger = "0.9.0"
lockfree = "0.5.1"
crossbeam = "0.8.1"
bytes = "1.1.0"
libc = "0.2.102"
config = "0.12.0"
serde = "1.0.130"
vfio-bindings = "0.3.1"
leb128 = "*"
futures = "*"
tokio = { version = "1.0", features = [ "rt-multi-thread", "time", "fs", "macros", "net",] }

[build-dependencies]
tonic-build = "0.8"
prost-build = "0.11.0"
cbindgen = "0.20.0"