[package]
name = "tapasco"
version = "1.0.0"
authors = ["Jaco Hofmann <hofmann@esa.tu-darmstadt.de>"]
edition = "2021"

[lib]
crate-type = ["staticlib", "rlib"]

[profile.release]
opt-level = 3
codegen-units = 1
lto = "fat"

[features]
# There are no default features:
default = []
# Necessary when building `tapasco-debug` to make some things accessible that are usually hidden away:
tapasco-debug = []

[dependencies]
log = "0.4.21"
chrono = "0.4.38"
nix = {  version = "0.28.0", features = ["feature", "event", "ioctl"] }
memmap = "0.7.0"
getset = "0.1.2"
snafu = "0.8.2"
tonic = "0.11"
prost = "0.12.4"
env_logger = "0.11.3"
lockfree = "0.5.1"
crossbeam = "0.8.4"
bytes = "1.6.0"
libc = "0.2.153"
config = "0.14.0"
serde = "1.0.197"
vfio-bindings = "0.3.1"
leb128 = "*"
futures = "*"
tokio = { version = "1.37", features = [ "rt-multi-thread", "time", "fs", "macros", "net",] }

[build-dependencies]
tonic-build = "0.11"
prost-build = "0.12.4"
cbindgen = "0.26.0"
