[package]
name = "tapasco-debug"
version = "0.1.0"
authors = ["zyno42 <83068959+zyno42@users.noreply.github.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tui = { version = "0.19.0", default-features = false, features = ['crossterm'] }
crossterm = "0.27.0"
tapasco = { path = "../../../libtapasco", features = ["tapasco-debug"] }
snafu = "0.8.2"
chrono = "0.4.38"
log = "0.4.21"
env_logger = "0.11.3"
clap = { version = "4.5.4", features = ["derive"] }
memmap = "0.7.0"
unicode-width = "0.1.11"
