[package]
name = "json_to_status"
version = "0.1.0"
authors = ["Jaco Hofmann <hofmann@esa.tu-darmstadt.de>"]
edition = "2018"

[dependencies]
failure = "0.1.8"
log = "0.4.21"
common_failures = "0.2.0"
env_logger = "0.11.3"
clap = "4.5.4"
serde_json = "1.0.116"
serde = {version = "1.0.198", features = ["derive"]}
hex = "0.4.3"
prost = "0.12.4"
bytes = "1.6.0"
regex = "1.10.4"

[build-dependencies]
prost-build = "0.12.4"
