.TH itapasco 1 "July 13, 2017" "version 2017.1"  "USER COMMANDS"
.SH NAME
itapasco \- The Interactive Task Parallel System Composer
.SH SYNOPSIS
.B itapasco
[global option]* [job]*
.SH DESCRIPTION
A Swing-based GUI for tapasco. See tapasco(1) for details on the options.
.SH ENVIRONMENT
.TP
.B TAPASCO_HOME
.RS
Path to TaPaSCo root installation folder (where setup.sh is located).
.RE
.SH SEE ALSO
tapasco(1)
