.TH tapasco-reportviewer 1 "May 11, 2017" "version 2017.1"  "USER COMMANDS"
.SH NAME
tapasco-reportviewer \- Graphical viewer tool for TaPaSCo report files.
.SH SYNOPSIS
.B tapasco-logviewer [REPORTFILE]
.SH DESCRIPTION
Debugging tool, a Swing-based report viewing tool for TaPaSCo. Any report file
format "understood" by TaPaSCo will be shown as a key-value table.
.SH ENVIRONMENT
.TP
.B TAPASCO_HOME
.RS
Path to TaPaSCo root installation folder (where setup.sh is located).
.RE
.SH SEE ALSO
tapasco(1), itapasco(1)
